# Generated by Django 4.2.2 on 2023-06-22 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Course Created')),
                ('title', models.CharField(max_length=100, verbose_name='Course Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Course Slug')),
                ('overview', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('Course',),
                'verbose_name_plural': 'Course',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Subject Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Subject Slug')),
            ],
            options={
                'verbose_name': ('Subject',),
                'verbose_name_plural': 'Subject',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Module Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Module Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Module description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject'),
        ),
    ]
